### ISSUE TITLE
Search Parameter not processed correctly

### ISSUE THREAD

**Issue by thoughtgap** [mevdschee/ra-data-treeql#11]
Hi, Thanks for providing this and mentioning [PHP-CRUD-API](https://github.com/mevdschee/php-crud-api ) which I have been using for many years.

I am using a text search as stated in the docs.

```javascript
const accountListFilters = [
  <TextInput label="Search" source="q" />,
  <TextInput label="Name" source="name" defaultValue="Hello World" />,
];

export const AccountList = () => (
  <List filters={accountListFilters}>
...
```

Using the search field, the "q" parameter gets transformed into "search", and added as a filter string `&filter=search,eq,<searchterm>`.
Instead, it should be added as a "search" parameter `&search=<searchterm>`.

Your [code](https://github.com/nkappler/ra-data-treeql/blob/c3f42ce0eece1b4d2ad49456b8ea09b9b14fde06/src/index.ts#L88) for this looks fine. Can you reproduce this behaviour?

My temporary workaround is a http Client injection manipulating the URL.

```javascript
const httpClient = (url, options = {}) => {
  // Check if URL contains 'filter=search,eq,<searchterm>'
  const searchFilterRegex = /filter=search,eq,([^&]+)/;
  const match = searchFilterRegex.exec(url);

  if (match) {
    // Replace 'filter=search,eq,<searchterm>' with '&search=<searchterm>'
    url = url.replace(searchFilterRegex, `&search=${match[1]}`);
  }
  return fetchUtils.fetchJson(url, options);
};

const api24DataProvider = treeqlProvider(
  "<url>",
  httpClient
);
```

**Comment by nkappler** [comment]
Hi, thanks for reporting.

Unfortunately I am not able to reproduce it:

<img width="973" alt="grafik" src="https://github.com/nkappler/ra-data-treeql/assets/9429273/0c511529-9753-43bb-bd76-efa6b4e6896a">

Could you share a reproducable sample implementation?
Can you share your dataprovider implementation?

**Comment by nkappler** [comment]
Which version of react-admin and ra-data-treeql are you using?

**Comment by thoughtgap** [comment]
Hi, good to hear that it should work correctly out of the box.

I'll try to provide the sample implementation tonight.

Meanwhile here's my package.json:

```
{
  "name": "test-admin",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview",
    "type-check": "tsc --noEmit",
    "lint": "eslint --fix --ext .js,.jsx,.ts,.tsx ./src",
    "format": "prettier --write ./src"
  },
  "dependencies": {
    "@mui/icons-material": "^5.15.4",
    "ra-data-simple-rest": "^4.16.0",
    "ra-data-treeql": "^1.2.0",
    "react": "^18.2.0",
    "react-admin": "^4.16.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^18.16.1",
    "@types/react": "^18.0.22",
    "@types/react-dom": "^18.0.7",
    "@typescript-eslint/eslint-plugin": "^5.60.1",
    "@typescript-eslint/parser": "^5.60.1",
    "@vitejs/plugin-react": "^4.0.1",
    "eslint": "^8.43.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.8.8",
    "typescript": "^5.1.6",
    "vite": "^4.3.9"
  }
}
```

**Comment by thoughtgap** [comment]
You are right, it works in a minimal example out of the box. Sorry for bothering you!
I'll do some digging in my project.

**Comment by nkappler** [comment]
> Sorry for bothering you!

No worries, let me know if you have any more questions.
