### ISSUE TITLE
Better filter support

### ISSUE THREAD

**Issue by nkappler** [mevdschee/ra-data-treeql#5]
https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators

react-admin supports searching and complex filters, which currently are not supported by this dataprovider.

part of the fix will probably include a middleware on the php API mentioned here: mevdschee/php-crud-api#881

**Comment by mevdschee** [comment]
Hi Nikolaj, I implemented the requested middleware. I hope you like it. Kind regards, Maurits

**Comment by nkappler** [comment]
fixed via cf0b456d97ed1f25ed5dcbad15aaa98ab61d3cef
