### ISSUE TITLE
GitHub Pages for Code Coverage

### ISSUE THREAD

**Issue by nkappler** [mevdschee/ra-data-treeql#7]
Hi @mevdschee,

I am currently replicating all the changes from my fork in order to deprecate it, but I don't have access to this repo's settings...
Could you please [setup github pages](https://github.com/mevdschee/ra-data-treeql/settings/pages) for this repo to be deployed from the `coverage` branch's `root` directory?

Thanks! 👍

**Comment by nkappler** [comment]
by the way, have you worked with GitHub Actions?

Currently, updating the coverage report and branch is a manual workflow and whilst not being very complicated, I am sure it could be automated.

Do you have experience in this area?

**Comment by mevdschee** [comment]
@nkappler I could transfer the repository to you so that you can continue working on it on your own (Github) account. I don't have much time for all these side projects anyway.

**Comment by nkappler** [comment]
Sure, why not.
Do i need to delete my fork to avoid a naming conflict?

**Comment by mevdschee** [comment]
> Do i need to delete my fork to avoid a naming conflict?

Maybe.. I think renaming is enough though.. I'll transfer the repo right away. 

Take good care of it! ;-)

**Comment by mevdschee** [comment]
I can't transfer yet, as you haven't renamed it. Let me know when you have renamed (or deleted) it.

**Comment by nkappler** [comment]
> I can't transfer yet, as you haven't renamed it. Let me know when you have renamed (or deleted) it.

done

**Comment by nkappler** [comment]
> Take good care of it! ;-)

Will do :+1:

**Comment by mevdschee** [comment]
Still can't:

> ERROR: nkappler already has a repository in the mevdschee/ra-data-treeql network

**Comment by nkappler** [comment]
ok I'll delete my fork, maybe this helps

**Comment by mevdschee** [comment]
Yeah.. keep a (local) backup ;-)

**Comment by nkappler** [comment]
please try again now

**Comment by nkappler** [comment]
> Yeah.. keep a (local) backup ;-)

all changes are already in the original repo, too :-)

**Comment by nkappler** [comment]
Seems to have worked, thank you :)
