### ISSUE TITLE
useUpdate hook "wrong" response

### ISSUE THREAD

**Issue by chattago2002** [mevdschee/ra-data-treeql#8]
I need help about using the "useUpdate" hook.
This is the exact error I receive:
```
The response to 'update' must be like { data: { id: 123, ... } }, but the received data does not have an 'id' key. The dataProvider is probably wrong for 'update'
```

My code is the following (cleaned and simplified):
```
const [update, { isLoading, error }] = useUpdate();
const id = 1;
update(
    'users',
    { id, data: { field1: "test1", field2: "test2" } },
    {
        onSuccess: () => {
            notify('Users edit');
            redirect(`/users`);

        }
    }
)
```

If I use the React-Admin Edit component all is fine with the same resource but I need to use the hook separately. I noticed in both cases (using Edit component or the useUpdate hook) the response is "0" or "1" but with Edit component no errors are logged in console. The update operations on table are made but I have problems with onSuccess and onError handling.
Am I doing something wrong? Or are there some problems?

**Comment by nkappler** [comment]
From my understanding, you should always provide the old record in the `previousData` property to an update call.
At least in the Type Declarations this property is mandatory and in the code examples for [`useUpdate`](https://marmelab.com/react-admin/useUpdate.html) it is also present.
You can obtain the Record with the [`useRecordContext`](https://marmelab.com/react-admin/useRecordContext.html) hook or from your component's props.

However, I published a patch, which should also fix this issue, by always returning at least the id. Note though, that the returned Record will not include all properties, if `previousData` is ommited.

`useDelete` might be also affected, so I've fixed it there, too.

**Comment by chattago2002** [comment]
Thank you @nkappler , with latest update the "problem" seems to be fixed.

About useUpdate to have "previousData" as mandatory prop, probably this was my mistake... but I think that React-Admin documentation sometimes is too simplistic, leaves so much for granted.

Anyway thanks for your support.
